###### Importing Numpy

In [1]:
import numpy as np

### Array Creation
There are several ways to create arrays:
* You can create an array from Python list
* The other is from Python tuple

In [2]:
#One dimensional array
np.array([1, 2, 3, 4])  

# WRONG: np.array(1, 2, 3, 4)

#Two dimensional array
np.array([[1, 0, 0], [0, 1, 2]])  

#NOTE: There are two square brackets at opening and closing of nested list
#WRONG: np.array([1, 0, 0], [0, 1, 2])

    
#Using zeros, ones and empty
np.zeros((3,4)) #creates an array of zeros

np.ones((2, 4)) #creates an array of ones

np.empty((3, 3)) #creates an array whose initial content is random


array([[6.92691742e-310, 6.92691742e-310, 6.92691757e-310],
       [6.92691763e-310, 6.92691760e-310, 6.92691755e-310],
       [6.92691761e-310, 6.92691760e-310, 4.65248671e-310]])

### Create arrays using arange
* arange: creates an array consisting of a sequence of numbers

*__arange takes step in it's arguments while linspace takes the number of elements in it's arguments__*

In [15]:
#One dimensional
np.arange(10) 

#OUTPUT: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

np.arange(2, 6)

#OUTPUT: [2, 3, 4, 5]

np.arange(10, 50, 5)

#OUTPUT: [10, 15, 20, 25, 30, 35, 40, 45] ***arange takes a step of 5.

np.arange(0, 10, 3)

#OUTPUT: [0, 3, 6, 9] ***arange takes a step of 3

#Two dimensional
np.arange(12).reshape(3, 4) 

np.arange(10, 50, 5).reshape(4, 2)


array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

### Create arrays using linspace
* linspace: creates an array consisting of a sequence of numbers similar to arange

*__linspace takes number of elements in it's arguments instead of step like arange__*

In [22]:
#One dimensional
np.linspace(10, 500) 

#OUTPUT: [10, 20, 30, ... 480, 490, 500]

np.linspace(10, 500, 5)

#OUTPUT: [10., 132.5, 255., 377.5, 500.] ***By default no of elements is 50

#Two dimensional
np.linspace(10, 40, 4).reshape(2, 2)


array([[10., 20.],
       [30., 40.]])

### Basic Operations

In [45]:
a = np.arange(9).reshape(3, 3)
print('A\n', a)
b = np.arange(10,19, dtype=float).reshape(3, 3)
print('B\n', b)

A
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
B
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [48]:
#Addition
addition = a + b

#Subtraction
subtraction = b - a

#Division
division = a/2

#Elementwise Multiplication
multiplication = a * b

#Matrix multiplication
product = a @ b

#Exponent
exponent = a**2

b += a
# a += b #Not valid since int cannot store floating point numbers

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [58]:
a.resize(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a[1, 2]

5

### Shape Manipulation

In [70]:
a = np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
#reshape returns the array with a modified shape
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
#resize modifies the shape of the array itself
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
#ravel returns a flattened array
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])